apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mvd6genvs-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mvd6genvs-go 
  name: mvd6genvs-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mvd6genvs-go 
